### ISSUE TITLE
Raising because we don't have a provider

### ISSUE THREAD

**Issue by zachfeldman** [kortirso/emailbutler#19]
Hi there, we're using this gem without a webhook provider as we're just interested in the base functionality. When trying to upgrade to 0.8.0, we get this error:
```
Emailbutler::Configuration::InitializeError: At least 1 provider must be present (Emailbutler::Configuration::InitializeError)
```

Can you please make the provider optional again in 0.8.1? I can also work on a patch for this if you'd like. 
Thank you so much!

**Comment by kortirso** [comment]
@zachfeldman Hi, Zach, sorry for long response, are you interesting in just emails statistics and not receiving webhooks?

**Comment by zachfeldman** [comment]
@kortirso no problem, sorry for my long response. I was off last week!

Yes, that's exactly it, and your gem is really useful for just that without the webhooks (for us) :)

**Comment by zachfeldman** [comment]
Thanks @kortirso !

**Comment by kortirso** [comment]
> Thanks @kortirso !

you are welcome, thanks for using gem
