### ISSUE TITLE
uninitialized constant Emailbutler::ApplicationHelper::Pagy (NameError)

### ISSUE THREAD

**Issue by AlanMendicutti** [kortirso/emailbutler#2]
I'm getting this error in production mode only.

```
include Pagy::Frontend

/usr/local/bundle/gems/emailbutler-0.5.9/app/helpers/emailbutler/application_helper.rb:5:in `<module:ApplicationHelper>': uninitialized constant Emailbutler::ApplicationHelper::Pagy (NameError)

Unable to load application: NameError: uninitialized constant Emailbutler::ApplicationHelper::Pagy
```

And so the app fails at starting.
Does anybody know what might be causing it?

- Dev environment works like a charm.
- I'm not including a single pagination gem.
- The same error happens with 0.5.7 and 0.6.0

Thanks in advance.

**Comment by kortirso** [comment]
@AlanMendicutti  for real production apps I didn't see such error, and in such app we have included pagy gem, so maybe if project has it in its own gemfile then such error probably will not happen

but I released version 0.6.1 with better including pagy modules in emailbutler, maybe this will help without including apgy gem to application's gemfile
