### ISSUE TITLE
Future integrations

### ISSUE THREAD

**Issue by huda-kh** [kortirso/emailbutler#25]
I just found the gem and we would find it very useful in our application. Any plans to integrate with Mailtrap or Mandrill?

**Comment by kortirso** [comment]
hi @huda-kh, yes, there will be more integrations, what do you need first?

**Comment by huda-kh** [comment]
> hi @huda-kh, yes, there will be more integrations, what do you need first?

Awesome! We are currently using Mandrill so it would be good to have it for that. We are considering migrating to Mailtrap but were missing the resend functionality which your gem will fix for us! We can even

**Comment by huda-kh** [comment]
> and Mandrill/Mailchimp is the same thing right now?

Yes. Mandrill is Mailchimp transactional.

**Comment by kortirso** [comment]
Mailtrap is ready in master branch (not released yet)
For Mandrill - while you use it already, can you please provide simple example of webhook's payload that they send?

**Comment by huda-kh** [comment]
> Mailtrap is ready in master branch (not released yet) 

Thank you! I look forward to testing this soon!

> For Mandrill - while you use it already, can you please provide simple example of webhook's payload that they send?

We don't use webhooks at the moment, but I've just created a test webhook to RequestBin and collected the following payload:

```json
{
    "method": "POST",
    "path": "/",
    "query": {},
    "client_ip": "54.200.104.58",
    "url": "https://eoqsnnupxdtc3n2.m.pipedream.net/",
    "headers": {
        "host": "eoqsnnupxdtc3n2.m.pipedream.net",
        "content-length": "626",
        "user-agent": "Mandrill-Webhook/1.0",
        "accept": "*/*",
        "x-mandrill-signature": "KLag92NINqXIV9/ZIcU5E5EbajM=",
        "content-type": "application/x-www-form-urlencoded"
    },
    "body": {
        "mandrill_events": "[{\"event\":\"send\",\"_id\":\"a6eaeacb1fa242e1a66dcb0cfde56e4d\",\"msg\":{\"ts\":1727307654,\"subject\":\"Test email\",\"email\":\"user@domain.com\",\"tags\":[],\"opens\":[],\"clicks\":[],\"state\":\"sent\",\"smtp_events\":[],\"subaccount\":null,\"resends\":[],\"reject\":null,\"_id\":\"a6eaeacb1fa242e1a66dcb0cfde56e4d\",\"sender\":\"no-reply@ourdomain.com\",\"template\":null},\"ts\":1727307654}]"
    }
}
```
